"""Run the HyperMesh meshing workflow without an AI agent.

This script is a thin deterministic runner over the existing MCP functions in
``hypermesh_mcp_server.py``. It assumes a visible HyperMesh session has already
sourced the GUI listener Tcl generated by ``create_gui_listener_tcl``.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from pathlib import Path
from typing import Any

import hypermesh_mcp_server as hm


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")


ROOT = Path(__file__).resolve().parent
RUNS_DIR = ROOT / "runs"
OUTPUTS_DIR = ROOT / "outputs"


def _now_stamp() -> str:
    return time.strftime("%Y%m%d_%H%M%S")


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _write_json_if_enabled(enabled: bool, path: Path, payload: Any) -> str | None:
    if not enabled:
        return None
    _write_json(path, payload)
    return str(path)


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def _log(message: str) -> None:
    print(message, flush=True)


def _drag_distance(item: dict[str, Any]) -> float:
    axis = str(item.get("drag_axis") or item.get("axis") or "z").lower()
    dims = item.get("dims") if isinstance(item.get("dims"), dict) else {}
    key = {"x": "dx", "y": "dy", "z": "dz"}.get(axis, "dz")
    return float(dims.get(key) or dims.get("mn") or 0.0)


def _build_drag_solids(results: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    solids: list[dict[str, Any]] = []
    for key, item in sorted(results.items(), key=lambda pair: int(pair[0])):
        if item.get("strategy") != "drag_hex":
            continue
        solids.append(
            {
                "solid_id": int(item["solid_id"]),
                "source_surface_id": int(item.get("source_surface_id", 0)),
                "drag_distance": _drag_distance(item),
                "component_name": str(item["component_name"]),
                "axis": str(item.get("drag_axis") or "z"),
            }
        )
    return solids


def _build_tetra_batches(classification: dict[str, Any]) -> list[dict[str, Any]]:
    return list(classification.get("phase3_tetra_batches") or [])


def _tcl_braced(value: Any) -> str:
    text = str(value if value is not None else "")
    return "{" + text.replace("\\", "\\\\").replace("}", "\\}") + "}"


def _detect_existing_mesh_by_solid(
    results: dict[str, dict[str, Any]],
    *,
    host: str,
    port: int,
    timeout_seconds: int,
) -> dict[str, dict[str, Any]]:
    solid_ids = [int(key) for key in sorted(results, key=lambda value: int(value))]
    if not solid_ids:
        return {}
    solid_list = " ".join(str(sid) for sid in solid_ids)
    script = f"""
puts "MCP_EXISTING_MESH_BEGIN"
foreach sid {{{solid_list}}} {{
    set comp_name ""
    set elem_count 0
    *createmark components 1 "by solids" $sid
    set cids [hm_getmark components 1]
    if {{[llength $cids] > 0}} {{
        set cid [lindex $cids 0]
        catch {{set comp_name [hm_getvalue components id=$cid dataname=name]}}
        catch {{
            *createmark elements 1 "by comp" "$comp_name"
            set elem_count [llength [hm_getmark elements 1]]
        }}
    }}
    puts "MCP_EXISTING_MESH solid=$sid elems=$elem_count comp=<$comp_name>"
}}
puts "MCP_EXISTING_MESH_END"
""".lstrip()
    response = hm.execute_tcl_gui(
        script,
        host=host,
        port=port,
        timeout_seconds=timeout_seconds,
        enforce_meshing_rules=False,
    )
    text = str(response.get("response", "") or response.get("stdout", ""))
    detected: dict[str, dict[str, Any]] = {}
    for line in text.splitlines():
        match = re.search(r"MCP_EXISTING_MESH solid=(\d+) elems=(\d+) comp=<([^>]*)>", line)
        if not match:
            continue
        sid, elems, comp = match.group(1), int(match.group(2)), match.group(3)
        detected[sid] = {
            "solid_id": int(sid),
            "component_name": comp,
            "element_count": elems,
            "has_existing_mesh": elems > 0,
        }
    return detected


def _filter_tetra_batches_for_active_results(
    classification: dict[str, Any],
    active_results: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    active_ids = {int(key) for key in active_results}
    filtered: list[dict[str, Any]] = []
    next_batch = 1
    for batch in _build_tetra_batches(classification):
        solid_ids = [int(value) for value in batch.get("solid_ids", []) if int(value) in active_ids]
        if not solid_ids:
            continue
        filtered.append(
            {
                **batch,
                "batch": next_batch,
                "solid_ids": solid_ids,
            }
        )
        next_batch += 1
    return filtered


def _run_async_and_wait(
    *,
    script: str,
    log_path: Path,
    host: str,
    port: int,
    enqueue_timeout_seconds: int,
    run_timeout_seconds: int,
    enforce_meshing_rules: bool,
) -> dict[str, Any]:
    start = time.time()
    submit = hm.execute_tcl_gui_async(
        script,
        host=host,
        port=port,
        log_path=str(log_path),
        enqueue_timeout_seconds=enqueue_timeout_seconds,
        enforce_meshing_rules=enforce_meshing_rules,
    )
    result: dict[str, Any] = {
        "submit": submit,
        "log_path": str(log_path),
        "elapsed_seconds": None,
        "status": "submit_error",
        "tail": "",
    }
    if not submit.get("success"):
        result["elapsed_seconds"] = round(time.time() - start, 2)
        return result

    while True:
        text = _read_text(log_path)
        if "MCP_ASYNC_OK" in text:
            result.update(
                {
                    "status": "ok",
                    "elapsed_seconds": round(time.time() - start, 2),
                    "tail": text[-6000:],
                }
            )
            return result
        if "MCP_ASYNC_ERROR" in text:
            result.update(
                {
                    "status": "error",
                    "elapsed_seconds": round(time.time() - start, 2),
                    "tail": text[-6000:],
                }
            )
            return result
        if time.time() - start > run_timeout_seconds:
            result.update(
                {
                    "status": "timeout",
                    "elapsed_seconds": round(time.time() - start, 2),
                    "tail": text[-6000:],
                }
            )
            return result
        time.sleep(10)


def _parse_repair_summary(plan: dict[str, Any]) -> dict[str, Any]:
    repair: dict[str, dict[str, Any]] = {}
    tetra_done: dict[str, dict[str, int]] = {}

    for batch in plan.get("tetra_batches", []):
        text = _read_text(Path(batch["log_path"]))
        current_step: dict[str, str] = {}
        for line in text.splitlines():
            match = re.search(r"MCP_PT_FAIL solid=(\d+) .*delete_tetra_keep_surface_shells=1", line)
            if match:
                sid = match.group(1)
                repair.setdefault(sid, {})["tetra_deleted_keep_surface_shells"] = 1
                continue

            match = re.search(r"MCP_PT_QUALITY_FAIL solid=(\d+) bad_volume_elements=(\d+) kept_surface_shells=1", line)
            if match:
                sid = match.group(1)
                repair.setdefault(sid, {})["tetra_deleted_keep_surface_shells"] = 1
                repair.setdefault(sid, {})["bad_volume_elements_when_rolled_back"] = int(match.group(2))
                continue

            match = re.search(
                r"MCP_PT_STOP solid=(\d+) crash_guard_skip_tetmesh shell_count=(\d+) "
                r"limit=(\d+) unfixed_aspect=(\d+) keep_repaired_surface_mesh=1",
                line,
            )
            if match:
                sid = match.group(1)
                repair.setdefault(sid, {})["crash_guard_keep_surface_mesh"] = 1
                repair.setdefault(sid, {})["crash_guard_shell_count"] = int(match.group(2))
                repair.setdefault(sid, {})["crash_guard_limit"] = int(match.group(3))
                repair.setdefault(sid, {})["final_bad"] = int(match.group(4))
                repair.setdefault(sid, {})["vol_skew_initial_bad"] = 0
                repair.setdefault(sid, {})["vol_skew_final_bad"] = 0
                repair.setdefault(sid, {})["tetra_not_attempted_reason"] = "crash_guard_skip_tetmesh"
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) aspect_bad_local=(\d+)", line)
            if match:
                sid, bad = match.group(1), int(match.group(2))
                repair.setdefault(sid, {})["initial_bad"] = bad
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) aspect_repair=(\w+) count=(\d+)", line)
            if match:
                sid, step, count = match.group(1), match.group(2), int(match.group(3))
                current_step[sid] = step
                repair.setdefault(sid, {})[step] = {"before_count": count}
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) aspect_repair_after before=(\d+) after=(\d+)", line)
            if match:
                sid, before, after = match.group(1), int(match.group(2)), int(match.group(3))
                step = current_step.get(sid, "unknown")
                repair.setdefault(sid, {})[step] = {
                    "before": before,
                    "after": after,
                    "repaired": max(0, before - after),
                }
                repair[sid]["final_bad"] = after
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) replace_nodes_changed=(\d+)", line)
            if match:
                repair.setdefault(match.group(1), {})["replace_nodes_changed"] = int(match.group(2))
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) local_remesh_new_shells=(\d+)", line)
            if match:
                repair.setdefault(match.group(1), {})["local_remesh_new_shells"] = int(match.group(2))
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) vol_skew_bad_initial=(\d+) threshold=([0-9.eE+-]+)", line)
            if match:
                sid = match.group(1)
                repair.setdefault(sid, {})["vol_skew_initial_bad"] = int(match.group(2))
                repair.setdefault(sid, {})["vol_skew_threshold"] = float(match.group(3))
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) vol_skew_repair=([A-Za-z0-9_]+) count=(\d+)", line)
            if match:
                sid, step, count = match.group(1), match.group(2), int(match.group(3))
                current_step[f"{sid}:vol"] = step
                repair.setdefault(sid, {}).setdefault("vol_skew_repairs", {})[step] = {"before_count": count}
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) vol_skew_repair_after before=(\d+) after=(\d+) threshold=([0-9.eE+-]+)", line)
            if match:
                sid = match.group(1)
                before, after = int(match.group(2)), int(match.group(3))
                step = current_step.get(f"{sid}:vol", "unknown")
                repair.setdefault(sid, {}).setdefault("vol_skew_repairs", {})[step] = {
                    "before": before,
                    "after": after,
                    "repaired": max(0, before - after),
                }
                repair.setdefault(sid, {})["vol_skew_final_bad"] = after
                repair.setdefault(sid, {})["vol_skew_threshold"] = float(match.group(4))
                continue

            match = re.search(
                r"MCP_PT_DONE solid=(\d+) ok=(\d+) total=(\d+) tet4=(\d+).*"
                r"unfixed_aspect=(\d+).*unrepaired_vol_skew_over_([0-9.eE+-]+)=(\d+)",
                line,
            )
            if match:
                tetra_done[match.group(1)] = {
                    "ok": int(match.group(2)),
                    "total": int(match.group(3)),
                    "tet4": int(match.group(4)),
                    "unfixed_aspect": int(match.group(5)),
                    "unrepaired_vol_skew_threshold": float(match.group(6)),
                    "unrepaired_vol_skew": int(match.group(7)),
                }
                repair.setdefault(match.group(1), {})["vol_skew_final_bad"] = int(match.group(7))
                repair.setdefault(match.group(1), {})["vol_skew_threshold"] = float(match.group(6))

    aggregate = {
        "initial_bad": 0,
        "triangle_cleanup_repaired": 0,
        "smooth_5_repaired": 0,
        "local_remesh_repaired": 0,
        "replace_nodes_repaired": 0,
        "final_bad": 0,
        "replace_nodes_changed": 0,
        "local_remesh_new_shells": 0,
        "vol_skew_initial_bad": 0,
        "vol_skew_final_bad": 0,
        "vol_skew_solid_mesh_optimization_repaired": 0,
        "vol_skew_smooth_3_repaired": 0,
        "vol_skew_smooth_8_repaired": 0,
        "vol_skew_smooth_15_repaired": 0,
        "tetra_deleted_keep_surface_shells_count": 0,
        "bad_volume_elements_when_rolled_back": 0,
        "crash_guard_keep_surface_mesh_count": 0,
        "crash_guard_unfixed_aspect_count": 0,
    }
    for item in repair.values():
        aggregate["initial_bad"] += int(item.get("initial_bad") or 0)
        aggregate["final_bad"] += int(item.get("final_bad") or 0)
        aggregate["replace_nodes_changed"] += int(item.get("replace_nodes_changed") or 0)
        aggregate["local_remesh_new_shells"] += int(item.get("local_remesh_new_shells") or 0)
        aggregate["vol_skew_initial_bad"] += int(item.get("vol_skew_initial_bad") or 0)
        aggregate["vol_skew_final_bad"] += int(item.get("vol_skew_final_bad") or 0)
        aggregate["tetra_deleted_keep_surface_shells_count"] += int(item.get("tetra_deleted_keep_surface_shells") or 0)
        aggregate["bad_volume_elements_when_rolled_back"] += int(item.get("bad_volume_elements_when_rolled_back") or 0)
        aggregate["crash_guard_keep_surface_mesh_count"] += int(item.get("crash_guard_keep_surface_mesh") or 0)
        if int(item.get("crash_guard_keep_surface_mesh") or 0) > 0:
            aggregate["crash_guard_unfixed_aspect_count"] += int(item.get("final_bad") or 0)
        for step in ("triangle_cleanup", "smooth_5", "local_remesh", "replace_nodes"):
            value = item.get(step)
            if isinstance(value, dict):
                aggregate[f"{step}_repaired"] += int(value.get("repaired") or 0)
        vol_repairs = item.get("vol_skew_repairs", {})
        if isinstance(vol_repairs, dict):
            for step in ("solid_mesh_optimization", "smooth_3", "smooth_8", "smooth_15"):
                value = vol_repairs.get(step)
                if isinstance(value, dict):
                    aggregate[f"vol_skew_{step}_repaired"] += int(value.get("repaired") or 0)

    return {
        "repair_by_solid": repair,
        "repair_aggregate": aggregate,
        "tetra_attempted_count": len(tetra_done),
        "tetra_done_count": sum(1 for item in tetra_done.values() if item.get("ok") == 1 and item.get("tet4", 0) > 0),
        "tetra_failed_count": sum(1 for item in tetra_done.values() if item.get("ok") != 1 or item.get("tet4", 0) <= 0),
        "tetra_tet4_total": sum(item["tet4"] for item in tetra_done.values()),
        "tetra_done": tetra_done,
    }


def _parse_drag_actual_parameters(response_text: str) -> dict[str, dict[str, Any]]:
    actual: dict[str, dict[str, Any]] = {}
    for line in str(response_text or "").splitlines():
        match = re.search(
            r"MCP_DRAG_SIZE solid=(\d+) .*?requested=([0-9.eE+-]+) .*?chosen=([0-9.eE+-]+) limits=([0-9.eE+-]+)\.\.([0-9.eE+-]+)",
            line,
        )
        if match:
            actual[match.group(1)] = {
                "requested_element_size": float(match.group(2)),
                "actual_chosen_element_size": float(match.group(3)),
                "element_size_min": float(match.group(4)),
                "element_size_max": float(match.group(5)),
            }
    return actual


def _parse_tetra_actual_parameters(plan: dict[str, Any]) -> dict[str, dict[str, Any]]:
    actual: dict[str, dict[str, Any]] = {}
    for batch in plan.get("tetra_batches", []):
        text = _read_text(Path(batch["log_path"]))
        for line in text.splitlines():
            match = re.search(
                r"MCP_PT_START solid=(\d+) surf_count=(\d+) elem_size=([0-9.eE+-]+) "
                r"min_size=([0-9.eE+-]+) max_dev=([0-9.eE+-]+) fit_tol_ratio=([0-9.eE+-]+) "
                r"target_vol_skew=([0-9.eE+-]+)",
                line,
            )
            if match:
                actual[match.group(1)] = {
                    "surf_count": int(match.group(2)),
                    "actual_element_size": float(match.group(3)),
                    "actual_min_element_size": float(match.group(4)),
                    "max_deviation": float(match.group(5)),
                    "fit_tolerance_ratio": float(match.group(6)),
                    "target_vol_skew": float(match.group(7)),
                }
    return actual


def _build_part_parameter_report(
    *,
    results: dict[str, dict[str, Any]],
    drag_solids: list[dict[str, Any]],
    drag_response: dict[str, Any] | None,
    plan: dict[str, Any],
    args: argparse.Namespace,
) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    drag_actual = _parse_drag_actual_parameters(str((drag_response or {}).get("response", "")))
    tetra_actual = _parse_tetra_actual_parameters(plan)
    drag_ids = {int(item["solid_id"]) for item in drag_solids}

    for solid in drag_solids:
        sid = int(solid["solid_id"])
        actual = drag_actual.get(str(sid), {})
        items.append(
            {
                "solid_id": sid,
                "component_name": solid.get("component_name", ""),
                "strategy": "drag_hex",
                "axis": solid.get("axis", ""),
                "drag_distance": solid.get("drag_distance"),
                "requested_element_size": actual.get("requested_element_size", args.drag_element_size),
                "actual_element_size": actual.get("actual_chosen_element_size"),
                "element_size_min": actual.get("element_size_min", args.drag_element_size_min),
                "element_size_max": actual.get("element_size_max", args.drag_element_size_max),
                "fit_tolerance_ratio": args.drag_fit_tolerance_ratio,
                "retry_count": args.drag_retry_count,
            }
        )

    for key, info in sorted(results.items(), key=lambda pair: int(pair[0])):
        sid = int(key)
        if sid in drag_ids:
            continue
        strategy = str(info.get("strategy", ""))
        if "tetra" not in strategy:
            continue
        actual = tetra_actual.get(str(sid), {})
        items.append(
            {
                "solid_id": sid,
                "component_name": info.get("component_name", ""),
                "strategy": strategy,
                "surf_count": actual.get("surf_count", info.get("surf_count")),
                "requested_element_size": info.get("element_size", args.tetra_element_size),
                "actual_element_size": actual.get("actual_element_size"),
                "element_size_min": args.tetra_element_size_min,
                "element_size_max": args.tetra_element_size_max,
                "requested_min_element_size": info.get("min_element_size", args.tetra_min_element_size),
                "actual_min_element_size": actual.get("actual_min_element_size"),
                "min_element_size_min": args.tetra_min_element_size_min,
                "min_element_size_max": args.tetra_min_element_size_max,
                "max_deviation": actual.get("max_deviation", args.tetra_max_deviation),
                "feature_angle": args.tetra_feature_angle,
                "growth_rate": args.tetra_growth_rate,
                "fit_tolerance_ratio": actual.get("fit_tolerance_ratio", args.tetra_fit_tolerance_ratio),
                "target_vol_skew": actual.get("target_vol_skew", args.tetra_target_vol_skew),
                "repair_vol_skew": args.tetra_repair_vol_skew,
            }
        )

    return items


def _final_save_and_count(*, output_path: Path, host: str, port: int, timeout_seconds: int) -> dict[str, Any]:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_tcl_path = str(output_path).replace("\\", "/")
    script = f"""
puts "MCP_FINAL_SAVE_BEGIN"
*writefile "{output_tcl_path}" 1
puts "MCP_FINAL_SAVE_DONE path={output_tcl_path}"
*createmark elems 1 all
set all_elems [hm_getmark elems 1]
set shell_count 0
set tet4_count 0
set hex8_count 0
set other_count 0
foreach e $all_elems {{
    set cfg [hm_getvalue elems id=$e dataname=config]
    if {{$cfg == 103 || $cfg == 104 || $cfg == 106 || $cfg == 108}} {{incr shell_count}}
    if {{$cfg == 204}} {{incr tet4_count}}
    if {{$cfg == 208}} {{incr hex8_count}}
    if {{!($cfg == 103 || $cfg == 104 || $cfg == 106 || $cfg == 108 || $cfg == 204 || $cfg == 208)}} {{incr other_count}}
}}
puts "MCP_FINAL_COUNTS elems=[llength $all_elems] shells=$shell_count tet4=$tet4_count hex8=$hex8_count other=$other_count"
""".lstrip()
    start = time.time()
    result = hm.execute_tcl_gui(
        script,
        host=host,
        port=port,
        timeout_seconds=timeout_seconds,
        enforce_meshing_rules=False,
    )
    result["elapsed_seconds"] = round(time.time() - start, 2)
    result["output_hm_path"] = str(output_path)
    result["output_exists"] = output_path.exists()
    return result


def _isolate_rolled_back_solids(
    rolled_back_solids: list[dict[str, Any]],
    repair_summary: dict[str, Any],
    *,
    host: str,
    port: int,
    timeout_seconds: int,
) -> dict[str, Any]:
    if not rolled_back_solids:
        return {"success": True, "skipped": True}

    solid_ids = " ".join(str(item["solid_id"]) for item in rolled_back_solids)
    message_lines = ["退回到 2D 面网格的部件："]
    repair_by_solid = repair_summary.get("repair_by_solid", {})
    for item in rolled_back_solids:
        sid = str(item["solid_id"])
        info = repair_by_solid.get(sid, {})
        name = item.get("component_name") or "未命名"
        message_lines.extend(
            [
                "",
                f"solid {sid}（{name}）",
                f"2D 最开始不合格单元数量：{int(info.get('initial_bad') or 0)}",
                f"2D 修复后不合格单元数量：{int(info.get('final_bad') or 0)}",
                f"3D 最开始不合格单元数量：{int(info.get('vol_skew_initial_bad') or 0)}",
                f"3D 修复后不合格单元数量：{int(info.get('vol_skew_final_bad') or 0)}",
            ]
        )
        if int(info.get("crash_guard_keep_surface_mesh") or 0) > 0:
            message_lines.append(
                "3D 状态：未进入 tetra，shell 数量 "
                f"{int(info.get('crash_guard_shell_count') or 0)} 超过防崩阈值 "
                f"{int(info.get('crash_guard_limit') or 0)}，已保留修复后的 2D 面网格。"
            )
    message = "\n".join(message_lines)
    message_tcl = _tcl_braced(message)
    script = f"""
puts "MCP_ROLLBACK_ISOLATE_BEGIN solids={solid_ids}"
catch {{
    *createmark components 1 all
    *hideentitybymark components 1
}}
catch {{
    *createmark components 1 all
    *maskentitymark components 1 0
}}
foreach sid {{{solid_ids}}} {{
    catch {{
        *createmark components 1 "by solids" $sid
        *showentitybymark components 1
    }}
    catch {{
        *createmark components 1 "by solids" $sid
        *unmaskentitymark components 1 0
    }}
}}
catch {{tk_messageBox -title "网格退回提醒" -icon warning -type ok -message {message_tcl}}}
puts "MCP_ROLLBACK_ISOLATE_DONE solids={solid_ids}"
""".lstrip()
    return hm.execute_tcl_gui(
        script,
        host=host,
        port=port,
        timeout_seconds=timeout_seconds,
        enforce_meshing_rules=False,
    )


def run_workflow(args: argparse.Namespace) -> dict[str, Any]:
    stamp = args.stamp or _now_stamp()
    RUNS_DIR.mkdir(exist_ok=True)
    OUTPUTS_DIR.mkdir(exist_ok=True)

    output_path = Path(args.output).resolve() if args.output else OUTPUTS_DIR / f"full_mesh_{stamp}.hm"
    report_path = RUNS_DIR / f"workflow_report_{stamp}.txt"

    workflow: dict[str, Any] = {
        "stamp": stamp,
        "host": args.host,
        "port": args.port,
        "output_hm_path": str(output_path),
        "continue_on_error": args.continue_on_error,
        "steps": {},
        "errors": [],
        "warnings": [],
    }

    _log(f"[1/6] Probe current HyperMesh model: {stamp}")
    probe_path = RUNS_DIR / f"workflow_probe_{stamp}.txt"
    probe = hm.run_geometry_probe_gui(
        host=args.host,
        port=args.port,
        output_path=str(probe_path),
        timeout_seconds=args.probe_timeout,
    )
    workflow["steps"]["probe"] = {
        "success": probe.get("success"),
        "output_file": probe.get("output_file"),
        "line_count": len(str(probe.get("probe_lines") or "").splitlines()),
        "debug_result": probe.get("_debug_result"),
    }
    _write_json_if_enabled(args.write_json, RUNS_DIR / f"workflow_probe_response_{stamp}.json", probe)
    if not probe.get("success"):
        raise RuntimeError("Geometry probe failed. See probe output and console log.")

    _log("[2/6] Classify solids and execute Phase 2 finalization")
    classification = hm.classify_all_solids_from_probe(probe.get("probe_lines", ""))
    _write_json_if_enabled(args.write_json, RUNS_DIR / f"workflow_classification_{stamp}.json", classification)
    workflow["steps"]["classification"] = {
        "success": classification.get("success"),
        "total_solids": classification.get("total_solids"),
        "strategy_counts": classification.get("strategy_counts"),
    }
    if not classification.get("success"):
        raise RuntimeError("Classification failed.")

    results = classification["results"]
    existing_mesh = _detect_existing_mesh_by_solid(
        results,
        host=args.host,
        port=args.port,
        timeout_seconds=args.phase2_timeout,
    )
    skipped_existing_mesh = {
        sid: item for sid, item in existing_mesh.items()
        if item.get("has_existing_mesh")
    }
    for sid, item in skipped_existing_mesh.items():
        if sid in results:
            results[sid]["skip_meshing"] = True
            results[sid]["skip_reason"] = "已有网格，自动跳过划分"
            results[sid]["existing_element_count"] = item.get("element_count", 0)
    active_results = {
        sid: item for sid, item in results.items()
        if not item.get("skip_meshing")
    }
    workflow["steps"]["existing_mesh_skip"] = {
        "skipped_count": len(skipped_existing_mesh),
        "skipped_solids": [
            {
                "solid_id": int(sid),
                "component_name": results.get(sid, {}).get("component_name") or item.get("component_name", ""),
                "element_count": item.get("element_count", 0),
            }
            for sid, item in sorted(skipped_existing_mesh.items(), key=lambda pair: int(pair[0]))
        ],
    }
    workflow["steps"]["classification"]["skipped_existing_mesh_count"] = len(skipped_existing_mesh)
    if skipped_existing_mesh:
        skipped_text = ", ".join(
            f"{sid}({item.get('element_count', 0)} elems)"
            for sid, item in sorted(skipped_existing_mesh.items(), key=lambda pair: int(pair[0]))
        )
        _log(f"  - skipped existing-mesh solids: {skipped_text}")

    phase2 = hm.execute_tcl_gui(
        classification["phase2_finalize_script"],
        host=args.host,
        port=args.port,
        timeout_seconds=args.phase2_timeout,
        enforce_meshing_rules=False,
    )
    _write_json_if_enabled(args.write_json, RUNS_DIR / f"workflow_phase2_response_{stamp}.json", phase2)
    workflow["steps"]["phase2_finalize"] = phase2
    if not phase2.get("success"):
        raise RuntimeError("Phase 2 finalization failed. See workflow_phase2_response JSON.")

    _log("[3/6] Run drag-hex solids")
    drag_solids = _build_drag_solids(active_results)
    drag_step: dict[str, Any] = {"count": len(drag_solids), "success": True}
    drag_response: dict[str, Any] | None = None
    if drag_solids:
        drag = hm.generate_batched_drag_hex_tcl(
            solids=drag_solids,
            element_size=args.drag_element_size,
            element_size_min=args.drag_element_size_min,
            element_size_max=args.drag_element_size_max,
            fit_tolerance_ratio=args.drag_fit_tolerance_ratio,
            retry_count=args.drag_retry_count,
            pause_seconds_after_each_solid=args.drag_pause_seconds,
            checkpoint_every_n_solids=0,
        )
        drag_script_path = RUNS_DIR / f"workflow_drag_hex_{stamp}.tcl"
        drag_script_path.write_text(drag["script"], encoding="utf-8")
        start = time.time()
        drag_response = hm.execute_tcl_gui(
            drag["script"],
            host=args.host,
            port=args.port,
            timeout_seconds=args.drag_timeout,
            enforce_meshing_rules=False,
        )
        drag_response["elapsed_seconds"] = round(time.time() - start, 2)
        drag_response_path = _write_json_if_enabled(
            args.write_json,
            RUNS_DIR / f"workflow_drag_hex_response_{stamp}.json",
            drag_response,
        )
        drag_step.update(
            {
                "success": drag_response.get("success"),
                "script_path": str(drag_script_path),
                "response_path": drag_response_path,
            }
        )
        if not drag_response.get("success"):
            workflow["errors"].append({"step": "drag_hex", "response": drag_response})
            if not args.continue_on_error:
                raise RuntimeError("Drag-hex step failed.")
    workflow["steps"]["drag_hex"] = drag_step

    _log("[4/6] Run tetra batches")
    tetra_batches = _filter_tetra_batches_for_active_results(classification, active_results)
    plan_batches: list[dict[str, Any]] = []
    tetra_step: dict[str, Any] = {"batch_count": len(tetra_batches), "completed": [], "failed": []}
    for batch in tetra_batches:
        batch_index = int(batch["batch"])
        solid_ids = [int(value) for value in batch["solid_ids"]]
        solids = [results[str(sid)] for sid in solid_ids]
        generated = hm.generate_batched_plain_tetra_tcl(
            solids=solids,
            pause_seconds_after_each_solid=args.tetra_pause_seconds,
            checkpoint_every_n_solids=0,
            default_element_size=args.tetra_element_size,
            default_min_element_size=args.tetra_min_element_size,
            max_deviation=args.tetra_max_deviation,
            feature_angle=args.tetra_feature_angle,
            growth_rate=args.tetra_growth_rate,
            fit_tolerance_ratio=args.tetra_fit_tolerance_ratio,
            target_vol_skew=args.tetra_target_vol_skew,
            repair_vol_skew=args.tetra_repair_vol_skew,
            element_size_min=args.tetra_element_size_min,
            element_size_max=args.tetra_element_size_max,
            min_element_size_min=args.tetra_min_element_size_min,
            min_element_size_max=args.tetra_min_element_size_max,
            delete_existing_component_elements=True,
        )
        script_path = RUNS_DIR / f"workflow_tetra_batch_{batch_index:02d}_{stamp}.tcl"
        log_path = RUNS_DIR / f"workflow_tetra_batch_{batch_index:02d}_{stamp}.log"
        script_path.write_text(generated["script"], encoding="utf-8")
        plan_batches.append(
            {
                "batch": batch_index,
                "solid_ids": solid_ids,
                "solid_names": {str(solid["solid_id"]): solid.get("component_name", "") for solid in solids},
                "script_path": str(script_path),
                "log_path": str(log_path),
                "reason": batch.get("reason", ""),
            }
        )
        _log(f"  - tetra batch {batch_index}/{len(tetra_batches)} solids={solid_ids}")
        result = _run_async_and_wait(
            script=generated["script"],
            log_path=log_path,
            host=args.host,
            port=args.port,
            enqueue_timeout_seconds=args.async_enqueue_timeout,
            run_timeout_seconds=args.tetra_timeout,
            enforce_meshing_rules=False,
        )
        tetra_response_path = _write_json_if_enabled(
            args.write_json,
            RUNS_DIR / f"workflow_tetra_batch_{batch_index:02d}_response_{stamp}.json",
            result,
        )
        if result["status"] == "ok":
            tetra_step["completed"].append(batch_index)
        else:
            failure = {
                "batch": batch_index,
                "solid_ids": solid_ids,
                "status": result["status"],
                "response_path": tetra_response_path,
            }
            tetra_step["failed"].append(failure)
            workflow["errors"].append({"step": "tetra", **failure})
            if not args.continue_on_error:
                raise RuntimeError(f"Tetra batch {batch_index} failed: {result['status']}")
    workflow["steps"]["tetra"] = tetra_step

    plan = {
        "stamp": stamp,
        "drag_count": len(drag_solids),
        "tetra_batches": plan_batches,
        "final_save_path": str(output_path),
    }
    _write_json_if_enabled(args.write_json, RUNS_DIR / f"workflow_execution_plan_{stamp}.json", plan)

    _log("[5/6] Final save and element count")
    final_save = _final_save_and_count(
        output_path=output_path,
        host=args.host,
        port=args.port,
        timeout_seconds=args.save_timeout,
    )
    _write_json_if_enabled(args.write_json, RUNS_DIR / f"workflow_final_save_response_{stamp}.json", final_save)
    workflow["steps"]["final_save"] = final_save

    _log("[6/6] Parse repair summary")
    repair_summary = _parse_repair_summary(plan)
    part_parameters = _build_part_parameter_report(
        results=active_results,
        drag_solids=drag_solids,
        drag_response=drag_response,
        plan=plan,
        args=args,
    )
    _write_json_if_enabled(args.write_json, RUNS_DIR / f"workflow_repair_summary_{stamp}.json", repair_summary)
    workflow["steps"]["repair_summary"] = {
        **repair_summary["repair_aggregate"],
        "tetra_attempted_count": repair_summary["tetra_attempted_count"],
        "tetra_done_count": repair_summary["tetra_done_count"],
        "tetra_failed_count": repair_summary["tetra_failed_count"],
        "tetra_tet4_total": repair_summary["tetra_tet4_total"],
    }
    rollback_count = int(repair_summary["repair_aggregate"].get("tetra_deleted_keep_surface_shells_count") or 0)
    crash_guard_count = int(repair_summary["repair_aggregate"].get("crash_guard_keep_surface_mesh_count") or 0)
    rolled_back_solids: list[dict[str, Any]] = []
    solid_name_by_id = {
        str(sid): name
        for batch in plan_batches
        for sid, name in (batch.get("solid_names") or {}).items()
    }
    for sid, info in sorted(repair_summary["repair_by_solid"].items(), key=lambda pair: int(pair[0])):
        if int(info.get("tetra_deleted_keep_surface_shells") or 0) > 0 or int(info.get("crash_guard_keep_surface_mesh") or 0) > 0:
            rolled_back_solids.append(
                {
                    "solid_id": int(sid),
                    "component_name": solid_name_by_id.get(str(sid), ""),
                    "bad_volume_elements": int(info.get("bad_volume_elements_when_rolled_back") or 0),
                    "crash_guard": int(info.get("crash_guard_keep_surface_mesh") or 0),
                    "crash_guard_shell_count": int(info.get("crash_guard_shell_count") or 0),
                    "crash_guard_limit": int(info.get("crash_guard_limit") or 0),
                }
            )
    if rollback_count:
        rollback_error = {
            "step": "tetra_quality",
            "status": "rolled_back_to_surface_mesh",
            "solid_count": rollback_count,
            "bad_volume_elements": repair_summary["repair_aggregate"].get("bad_volume_elements_when_rolled_back", 0),
            "solids": [item for item in rolled_back_solids if not item.get("crash_guard")],
        }
        workflow["errors"].append(rollback_error)
    if crash_guard_count:
        guard_error = {
            "step": "tetra_quality",
            "status": "crash_guard_keep_surface_mesh",
            "solid_count": crash_guard_count,
            "unfixed_aspect": repair_summary["repair_aggregate"].get("crash_guard_unfixed_aspect_count", 0),
            "solids": [item for item in rolled_back_solids if item.get("crash_guard")],
        }
        workflow["errors"].append(guard_error)
    if rolled_back_solids:
        solid_text = "，".join(
            f"solid {item['solid_id']}({item['component_name'] or '未命名'})"
            for item in rolled_back_solids
        )
        if crash_guard_count:
            workflow["warnings"].append(
                "警告：部分实体触发 tetra 防崩保护，未进入 3D tetra，已保留修复后的 2D 面网格。"
                f"触发实体：{solid_text or '未记录'}。"
                "详细信息见中文 TXT 报告。"
            )
        elif rollback_count:
            workflow["warnings"].append(
                "警告：3D tetra 质量修复后仍有不合格体单元；"
                f"{rollback_count} 个实体已删除 tetra 体网格并退回为仅保留 2D 面网格。"
                f"失败实体：{solid_text or '未记录'}。"
                "详细信息见中文 TXT 报告。"
            )

    workflow["success"] = (
        bool(final_save.get("success"))
        and bool(final_save.get("output_exists"))
        and not workflow["errors"]
    )
    report_data = {
        "stamp": stamp,
        "success": workflow["success"],
        "output_hm_path": str(output_path),
        "classification": workflow["steps"]["classification"],
        "drag_count": len(drag_solids),
        "tetra": tetra_step,
        "final_save": final_save,
        "repair_summary": repair_summary,
        "errors": workflow["errors"],
        "parameters": {
            "drag_element_size": args.drag_element_size,
            "drag_element_size_min": args.drag_element_size_min,
            "drag_element_size_max": args.drag_element_size_max,
            "drag_fit_tolerance_ratio": args.drag_fit_tolerance_ratio,
            "drag_retry_count": args.drag_retry_count,
            "tetra_element_size": args.tetra_element_size,
            "tetra_element_size_min": args.tetra_element_size_min,
            "tetra_element_size_max": args.tetra_element_size_max,
            "tetra_min_element_size": args.tetra_min_element_size,
            "tetra_min_element_size_min": args.tetra_min_element_size_min,
            "tetra_min_element_size_max": args.tetra_min_element_size_max,
            "tetra_max_deviation": args.tetra_max_deviation,
            "tetra_feature_angle": args.tetra_feature_angle,
            "tetra_growth_rate": args.tetra_growth_rate,
            "tetra_fit_tolerance_ratio": args.tetra_fit_tolerance_ratio,
            "tetra_target_vol_skew": args.tetra_target_vol_skew,
            "tetra_repair_vol_skew": args.tetra_repair_vol_skew,
        },
        "part_parameters": part_parameters,
        "skipped_existing_mesh": workflow["steps"].get("existing_mesh_skip", {}),
        "generated_files": {
            "探测结果": str(probe_path),
            "中文报告": str(report_path),
            "最终模型": str(output_path),
        },
    }
    report = hm.write_chinese_meshing_workflow_report(report_data, output_path=str(report_path))
    workflow["report_path"] = report.get("report_path")
    if rolled_back_solids:
        isolate_result = _isolate_rolled_back_solids(
            rolled_back_solids,
            repair_summary,
            host=args.host,
            port=args.port,
            timeout_seconds=args.phase2_timeout,
        )
        workflow["steps"]["rollback_isolation"] = {
            "success": isolate_result.get("success"),
            "solids": rolled_back_solids,
        }
    _write_json_if_enabled(args.write_json, RUNS_DIR / f"workflow_summary_{stamp}.json", workflow)
    _write_json_if_enabled(args.write_json, RUNS_DIR / "workflow_latest_summary.json", workflow)
    _log(f"Chinese report: {report.get('report_path')}")
    return workflow


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run the HyperMesh meshing workflow without an AI agent.",
    )
    parser.add_argument("--host", default="127.0.0.1", help="HyperMesh GUI listener host.")
    parser.add_argument("--port", type=int, default=hm.DEFAULT_GUI_PORT, help="HyperMesh GUI listener port.")
    parser.add_argument("--output", default=None, help="Final .hm output path. Defaults to outputs/full_mesh_<stamp>.hm.")
    parser.add_argument("--stamp", default=None, help="Optional run stamp for deterministic output filenames.")
    parser.add_argument("--continue-on-error", action="store_true", default=True, help="Record failed batches and continue.")
    parser.add_argument("--stop-on-error", dest="continue_on_error", action="store_false", help="Stop at the first failure.")
    parser.add_argument("--probe-timeout", type=int, default=180)
    parser.add_argument("--phase2-timeout", type=int, default=120)
    parser.add_argument("--drag-timeout", type=int, default=900)
    parser.add_argument("--tetra-timeout", type=int, default=1800)
    parser.add_argument("--save-timeout", type=int, default=300)
    parser.add_argument("--async-enqueue-timeout", type=int, default=10)
    parser.add_argument("--drag-element-size", type=float, default=1.0)
    parser.add_argument("--drag-element-size-min", type=float, default=0.5)
    parser.add_argument("--drag-element-size-max", type=float, default=1.5)
    parser.add_argument("--drag-fit-tolerance-ratio", type=float, default=0.05)
    parser.add_argument("--drag-retry-count", type=int, default=2)
    parser.add_argument("--drag-pause-seconds", type=float, default=0.5)
    parser.add_argument("--tetra-element-size", type=float, default=1.5)
    parser.add_argument("--tetra-element-size-min", type=float, default=1.5)
    parser.add_argument("--tetra-element-size-max", type=float, default=2.0)
    parser.add_argument("--tetra-min-element-size", type=float, default=0.5)
    parser.add_argument("--tetra-min-element-size-min", type=float, default=0.20)
    parser.add_argument("--tetra-min-element-size-max", type=float, default=0.50)
    parser.add_argument("--tetra-max-deviation", type=float, default=0.05)
    parser.add_argument("--tetra-feature-angle", type=float, default=15.0)
    parser.add_argument("--tetra-growth-rate", type=float, default=1.23)
    parser.add_argument("--tetra-fit-tolerance-ratio", type=float, default=0.01)
    parser.add_argument("--tetra-target-vol-skew", type=float, default=0.70)
    parser.add_argument("--tetra-repair-vol-skew", type=float, default=0.99)
    parser.add_argument("--tetra-pause-seconds", type=float, default=1.0)
    parser.add_argument("--write-json", action="store_true", help="Write detailed JSON debug files into runs/.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    try:
        summary = run_workflow(args)
    except Exception as exc:
        _log(f"ERROR: {exc}")
        return 1

    counts = summary.get("steps", {}).get("final_save", {}).get("response", "")
    _log(f"Success: {summary.get('success')}")
    if counts:
        for line in str(counts).splitlines():
            if line.startswith("MCP_FINAL_COUNTS"):
                _log(line)
    _log(f"Output: {summary.get('output_hm_path')}")
    _log(f"Report: {summary.get('report_path')}")
    warnings = summary.get("warnings") or []
    if warnings:
        _log("")
        for warning in warnings:
            _log(str(warning))
    return 0 if summary.get("success") else 2


if __name__ == "__main__":
    sys.exit(main())
