"""Run the HyperMesh meshing workflow without an AI agent.

This script is a thin deterministic runner over the existing MCP functions in
``hypermesh_mcp_server.py``. It assumes a visible HyperMesh session has already
sourced the GUI listener Tcl generated by ``create_gui_listener_tcl``.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
from pathlib import Path
from typing import Any

import hypermesh_mcp_server as hm


ROOT = Path(__file__).resolve().parent
RUNS_DIR = ROOT / "runs"
OUTPUTS_DIR = ROOT / "outputs"


def _now_stamp() -> str:
    return time.strftime("%Y%m%d_%H%M%S")


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""


def _log(message: str) -> None:
    print(message, flush=True)


def _drag_distance(item: dict[str, Any]) -> float:
    axis = str(item.get("drag_axis") or item.get("axis") or "z").lower()
    dims = item.get("dims") if isinstance(item.get("dims"), dict) else {}
    key = {"x": "dx", "y": "dy", "z": "dz"}.get(axis, "dz")
    return float(dims.get(key) or dims.get("mn") or 0.0)


def _build_drag_solids(results: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    solids: list[dict[str, Any]] = []
    for key, item in sorted(results.items(), key=lambda pair: int(pair[0])):
        if item.get("strategy") != "drag_hex":
            continue
        solids.append(
            {
                "solid_id": int(item["solid_id"]),
                "source_surface_id": int(item.get("source_surface_id", 0)),
                "drag_distance": _drag_distance(item),
                "component_name": str(item["component_name"]),
                "axis": str(item.get("drag_axis") or "z"),
            }
        )
    return solids


def _build_tetra_batches(classification: dict[str, Any]) -> list[dict[str, Any]]:
    return list(classification.get("phase3_tetra_batches") or [])


def _run_async_and_wait(
    *,
    script: str,
    log_path: Path,
    host: str,
    port: int,
    enqueue_timeout_seconds: int,
    run_timeout_seconds: int,
    enforce_meshing_rules: bool,
) -> dict[str, Any]:
    start = time.time()
    submit = hm.execute_tcl_gui_async(
        script,
        host=host,
        port=port,
        log_path=str(log_path),
        enqueue_timeout_seconds=enqueue_timeout_seconds,
        enforce_meshing_rules=enforce_meshing_rules,
    )
    result: dict[str, Any] = {
        "submit": submit,
        "log_path": str(log_path),
        "elapsed_seconds": None,
        "status": "submit_error",
        "tail": "",
    }
    if not submit.get("success"):
        result["elapsed_seconds"] = round(time.time() - start, 2)
        return result

    while True:
        text = _read_text(log_path)
        if "MCP_ASYNC_OK" in text:
            result.update(
                {
                    "status": "ok",
                    "elapsed_seconds": round(time.time() - start, 2),
                    "tail": text[-6000:],
                }
            )
            return result
        if "MCP_ASYNC_ERROR" in text:
            result.update(
                {
                    "status": "error",
                    "elapsed_seconds": round(time.time() - start, 2),
                    "tail": text[-6000:],
                }
            )
            return result
        if time.time() - start > run_timeout_seconds:
            result.update(
                {
                    "status": "timeout",
                    "elapsed_seconds": round(time.time() - start, 2),
                    "tail": text[-6000:],
                }
            )
            return result
        time.sleep(10)


def _parse_repair_summary(plan: dict[str, Any]) -> dict[str, Any]:
    repair: dict[str, dict[str, Any]] = {}
    tetra_done: dict[str, dict[str, int]] = {}

    for batch in plan.get("tetra_batches", []):
        text = _read_text(Path(batch["log_path"]))
        current_step: dict[str, str] = {}
        for line in text.splitlines():
            match = re.search(r"MCP_PT_INFO solid=(\d+) aspect_bad_local=(\d+)", line)
            if match:
                sid, bad = match.group(1), int(match.group(2))
                repair.setdefault(sid, {})["initial_bad"] = bad
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) aspect_repair=(\w+) count=(\d+)", line)
            if match:
                sid, step, count = match.group(1), match.group(2), int(match.group(3))
                current_step[sid] = step
                repair.setdefault(sid, {})[step] = {"before_count": count}
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) aspect_repair_after before=(\d+) after=(\d+)", line)
            if match:
                sid, before, after = match.group(1), int(match.group(2)), int(match.group(3))
                step = current_step.get(sid, "unknown")
                repair.setdefault(sid, {})[step] = {
                    "before": before,
                    "after": after,
                    "repaired": max(0, before - after),
                }
                repair[sid]["final_bad"] = after
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) replace_nodes_changed=(\d+)", line)
            if match:
                repair.setdefault(match.group(1), {})["replace_nodes_changed"] = int(match.group(2))
                continue

            match = re.search(r"MCP_PT_INFO solid=(\d+) local_remesh_new_shells=(\d+)", line)
            if match:
                repair.setdefault(match.group(1), {})["local_remesh_new_shells"] = int(match.group(2))
                continue

            match = re.search(
                r"MCP_PT_DONE solid=(\d+) ok=(\d+) total=(\d+) tet4=(\d+).*"
                r"unfixed_aspect=(\d+).*unrepaired_vol_skew_over_0.99=(\d+)",
                line,
            )
            if match:
                tetra_done[match.group(1)] = {
                    "ok": int(match.group(2)),
                    "total": int(match.group(3)),
                    "tet4": int(match.group(4)),
                    "unfixed_aspect": int(match.group(5)),
                    "unrepaired_vol_skew_over_0.99": int(match.group(6)),
                }

    aggregate = {
        "initial_bad": 0,
        "triangle_cleanup_repaired": 0,
        "smooth_5_repaired": 0,
        "local_remesh_repaired": 0,
        "replace_nodes_repaired": 0,
        "final_bad": 0,
        "replace_nodes_changed": 0,
        "local_remesh_new_shells": 0,
    }
    for item in repair.values():
        aggregate["initial_bad"] += int(item.get("initial_bad") or 0)
        aggregate["final_bad"] += int(item.get("final_bad") or 0)
        aggregate["replace_nodes_changed"] += int(item.get("replace_nodes_changed") or 0)
        aggregate["local_remesh_new_shells"] += int(item.get("local_remesh_new_shells") or 0)
        for step in ("triangle_cleanup", "smooth_5", "local_remesh", "replace_nodes"):
            value = item.get(step)
            if isinstance(value, dict):
                aggregate[f"{step}_repaired"] += int(value.get("repaired") or 0)

    return {
        "repair_by_solid": repair,
        "repair_aggregate": aggregate,
        "tetra_done_count": len(tetra_done),
        "tetra_tet4_total": sum(item["tet4"] for item in tetra_done.values()),
        "tetra_done": tetra_done,
    }


def _final_save_and_count(*, output_path: Path, host: str, port: int, timeout_seconds: int) -> dict[str, Any]:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_tcl_path = str(output_path).replace("\\", "/")
    script = f"""
puts "MCP_FINAL_SAVE_BEGIN"
*writefile "{output_tcl_path}" 1
puts "MCP_FINAL_SAVE_DONE path={output_tcl_path}"
*createmark elems 1 all
set all_elems [hm_getmark elems 1]
set shell_count 0
set tet4_count 0
set hex8_count 0
set other_count 0
foreach e $all_elems {{
    set cfg [hm_getvalue elems id=$e dataname=config]
    if {{$cfg == 103 || $cfg == 104 || $cfg == 106 || $cfg == 108}} {{incr shell_count}}
    if {{$cfg == 204}} {{incr tet4_count}}
    if {{$cfg == 208}} {{incr hex8_count}}
    if {{!($cfg == 103 || $cfg == 104 || $cfg == 106 || $cfg == 108 || $cfg == 204 || $cfg == 208)}} {{incr other_count}}
}}
puts "MCP_FINAL_COUNTS elems=[llength $all_elems] shells=$shell_count tet4=$tet4_count hex8=$hex8_count other=$other_count"
""".lstrip()
    start = time.time()
    result = hm.execute_tcl_gui(
        script,
        host=host,
        port=port,
        timeout_seconds=timeout_seconds,
        enforce_meshing_rules=False,
    )
    result["elapsed_seconds"] = round(time.time() - start, 2)
    result["output_hm_path"] = str(output_path)
    result["output_exists"] = output_path.exists()
    return result


def run_workflow(args: argparse.Namespace) -> dict[str, Any]:
    stamp = args.stamp or _now_stamp()
    RUNS_DIR.mkdir(exist_ok=True)
    OUTPUTS_DIR.mkdir(exist_ok=True)

    output_path = Path(args.output).resolve() if args.output else OUTPUTS_DIR / f"full_mesh_{stamp}.hm"
    summary_path = RUNS_DIR / f"workflow_summary_{stamp}.json"

    workflow: dict[str, Any] = {
        "stamp": stamp,
        "host": args.host,
        "port": args.port,
        "output_hm_path": str(output_path),
        "continue_on_error": args.continue_on_error,
        "steps": {},
        "errors": [],
    }

    _log(f"[1/6] Probe current HyperMesh model: {stamp}")
    probe_path = RUNS_DIR / f"workflow_probe_{stamp}.txt"
    probe = hm.run_geometry_probe_gui(
        host=args.host,
        port=args.port,
        output_path=str(probe_path),
        timeout_seconds=args.probe_timeout,
    )
    workflow["steps"]["probe"] = {
        "success": probe.get("success"),
        "output_file": probe.get("output_file"),
        "line_count": len(str(probe.get("probe_lines") or "").splitlines()),
        "debug_result": probe.get("_debug_result"),
    }
    _write_json(RUNS_DIR / f"workflow_probe_response_{stamp}.json", probe)
    if not probe.get("success"):
        raise RuntimeError("Geometry probe failed. See workflow_probe_response JSON.")

    _log("[2/6] Classify solids and execute Phase 2 finalization")
    classification = hm.classify_all_solids_from_probe(probe.get("probe_lines", ""))
    _write_json(RUNS_DIR / f"workflow_classification_{stamp}.json", classification)
    workflow["steps"]["classification"] = {
        "success": classification.get("success"),
        "total_solids": classification.get("total_solids"),
        "strategy_counts": classification.get("strategy_counts"),
    }
    if not classification.get("success"):
        raise RuntimeError("Classification failed. See workflow_classification JSON.")

    phase2 = hm.execute_tcl_gui(
        classification["phase2_finalize_script"],
        host=args.host,
        port=args.port,
        timeout_seconds=args.phase2_timeout,
        enforce_meshing_rules=False,
    )
    _write_json(RUNS_DIR / f"workflow_phase2_response_{stamp}.json", phase2)
    workflow["steps"]["phase2_finalize"] = phase2
    if not phase2.get("success"):
        raise RuntimeError("Phase 2 finalization failed. See workflow_phase2_response JSON.")

    results = classification["results"]

    _log("[3/6] Run drag-hex solids")
    drag_solids = _build_drag_solids(results)
    drag_step: dict[str, Any] = {"count": len(drag_solids), "success": True}
    if drag_solids:
        drag = hm.generate_batched_drag_hex_tcl(
            solids=drag_solids,
            element_size=args.drag_element_size,
            fit_tolerance_ratio=args.drag_fit_tolerance_ratio,
            retry_count=args.drag_retry_count,
            pause_seconds_after_each_solid=args.drag_pause_seconds,
            checkpoint_every_n_solids=0,
        )
        drag_script_path = RUNS_DIR / f"workflow_drag_hex_{stamp}.tcl"
        drag_script_path.write_text(drag["script"], encoding="utf-8")
        start = time.time()
        drag_response = hm.execute_tcl_gui(
            drag["script"],
            host=args.host,
            port=args.port,
            timeout_seconds=args.drag_timeout,
            enforce_meshing_rules=False,
        )
        drag_response["elapsed_seconds"] = round(time.time() - start, 2)
        _write_json(RUNS_DIR / f"workflow_drag_hex_response_{stamp}.json", drag_response)
        drag_step.update(
            {
                "success": drag_response.get("success"),
                "script_path": str(drag_script_path),
                "response_path": str(RUNS_DIR / f"workflow_drag_hex_response_{stamp}.json"),
            }
        )
        if not drag_response.get("success"):
            workflow["errors"].append({"step": "drag_hex", "response": drag_response})
            if not args.continue_on_error:
                raise RuntimeError("Drag-hex step failed.")
    workflow["steps"]["drag_hex"] = drag_step

    _log("[4/6] Run tetra batches")
    tetra_batches = _build_tetra_batches(classification)
    plan_batches: list[dict[str, Any]] = []
    tetra_step: dict[str, Any] = {"batch_count": len(tetra_batches), "completed": [], "failed": []}
    for batch in tetra_batches:
        batch_index = int(batch["batch"])
        solid_ids = [int(value) for value in batch["solid_ids"]]
        solids = [results[str(sid)] for sid in solid_ids]
        generated = hm.generate_batched_plain_tetra_tcl(
            solids=solids,
            pause_seconds_after_each_solid=args.tetra_pause_seconds,
            checkpoint_every_n_solids=0,
            delete_existing_component_elements=True,
        )
        script_path = RUNS_DIR / f"workflow_tetra_batch_{batch_index:02d}_{stamp}.tcl"
        log_path = RUNS_DIR / f"workflow_tetra_batch_{batch_index:02d}_{stamp}.log"
        script_path.write_text(generated["script"], encoding="utf-8")
        plan_batches.append(
            {
                "batch": batch_index,
                "solid_ids": solid_ids,
                "script_path": str(script_path),
                "log_path": str(log_path),
                "reason": batch.get("reason", ""),
            }
        )
        _log(f"  - tetra batch {batch_index}/{len(tetra_batches)} solids={solid_ids}")
        result = _run_async_and_wait(
            script=generated["script"],
            log_path=log_path,
            host=args.host,
            port=args.port,
            enqueue_timeout_seconds=args.async_enqueue_timeout,
            run_timeout_seconds=args.tetra_timeout,
            enforce_meshing_rules=False,
        )
        _write_json(RUNS_DIR / f"workflow_tetra_batch_{batch_index:02d}_response_{stamp}.json", result)
        if result["status"] == "ok":
            tetra_step["completed"].append(batch_index)
        else:
            failure = {
                "batch": batch_index,
                "solid_ids": solid_ids,
                "status": result["status"],
                "response_path": str(RUNS_DIR / f"workflow_tetra_batch_{batch_index:02d}_response_{stamp}.json"),
            }
            tetra_step["failed"].append(failure)
            workflow["errors"].append({"step": "tetra", **failure})
            if not args.continue_on_error:
                raise RuntimeError(f"Tetra batch {batch_index} failed: {result['status']}")
    workflow["steps"]["tetra"] = tetra_step

    plan = {
        "stamp": stamp,
        "drag_count": len(drag_solids),
        "tetra_batches": plan_batches,
        "final_save_path": str(output_path),
    }
    _write_json(RUNS_DIR / f"workflow_execution_plan_{stamp}.json", plan)

    _log("[5/6] Final save and element count")
    final_save = _final_save_and_count(
        output_path=output_path,
        host=args.host,
        port=args.port,
        timeout_seconds=args.save_timeout,
    )
    _write_json(RUNS_DIR / f"workflow_final_save_response_{stamp}.json", final_save)
    workflow["steps"]["final_save"] = final_save

    _log("[6/6] Parse repair summary")
    repair_summary = _parse_repair_summary(plan)
    _write_json(RUNS_DIR / f"workflow_repair_summary_{stamp}.json", repair_summary)
    workflow["steps"]["repair_summary"] = {
        "path": str(RUNS_DIR / f"workflow_repair_summary_{stamp}.json"),
        **repair_summary["repair_aggregate"],
        "tetra_done_count": repair_summary["tetra_done_count"],
        "tetra_tet4_total": repair_summary["tetra_tet4_total"],
    }

    workflow["success"] = (
        bool(final_save.get("success"))
        and bool(final_save.get("output_exists"))
        and not workflow["errors"]
    )
    _write_json(summary_path, workflow)
    _write_json(RUNS_DIR / "workflow_latest_summary.json", workflow)
    _log(f"Workflow summary: {summary_path}")
    return workflow


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run the HyperMesh meshing workflow without an AI agent.",
    )
    parser.add_argument("--host", default="127.0.0.1", help="HyperMesh GUI listener host.")
    parser.add_argument("--port", type=int, default=hm.DEFAULT_GUI_PORT, help="HyperMesh GUI listener port.")
    parser.add_argument("--output", default=None, help="Final .hm output path. Defaults to outputs/full_mesh_<stamp>.hm.")
    parser.add_argument("--stamp", default=None, help="Optional run stamp for deterministic output filenames.")
    parser.add_argument("--continue-on-error", action="store_true", default=True, help="Record failed batches and continue.")
    parser.add_argument("--stop-on-error", dest="continue_on_error", action="store_false", help="Stop at the first failure.")
    parser.add_argument("--probe-timeout", type=int, default=180)
    parser.add_argument("--phase2-timeout", type=int, default=120)
    parser.add_argument("--drag-timeout", type=int, default=900)
    parser.add_argument("--tetra-timeout", type=int, default=1800)
    parser.add_argument("--save-timeout", type=int, default=300)
    parser.add_argument("--async-enqueue-timeout", type=int, default=10)
    parser.add_argument("--drag-element-size", type=float, default=1.0)
    parser.add_argument("--drag-fit-tolerance-ratio", type=float, default=0.05)
    parser.add_argument("--drag-retry-count", type=int, default=2)
    parser.add_argument("--drag-pause-seconds", type=float, default=0.5)
    parser.add_argument("--tetra-pause-seconds", type=float, default=1.0)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    try:
        summary = run_workflow(args)
    except Exception as exc:
        _log(f"ERROR: {exc}")
        return 1

    counts = summary.get("steps", {}).get("final_save", {}).get("response", "")
    _log(f"Success: {summary.get('success')}")
    if counts:
        for line in str(counts).splitlines():
            if line.startswith("MCP_FINAL_COUNTS"):
                _log(line)
    _log(f"Output: {summary.get('output_hm_path')}")
    return 0 if summary.get("success") else 2


if __name__ == "__main__":
    sys.exit(main())
